root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./cmd/app/main.go"
  
  bin = "./tmp/app"
  
  
  exclude_dir = []
  
  include_ext = ["go", "env"]
  
  exclude_regex = []
  
  stop_on_error = true
  
  send_interrupt = false
  
  kill_delay = "0s"
  
  poll = true
  poll_interval = 1000

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true